### ISSUE TITLE
`get_emmeans()`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/marginaleffects#1276]
@mattansb,

I thinking about including a `get_emmeans()` function to convert `marginaleffects` into `emmeans` objects. Your recommended code for that here:V

https://github.com/vincentarelbundock/marginaleffects/issues/1232#issuecomment-2423620196

IIUC, that code might be dangerous in some cases, because you are not supplying the actual grid to `emmeans`, but rather supplying a list of unique vectors, and relying on `emmeans` to rebuild the grid internally. That assumes that the grid construction order is the same in `emmeans` and `marginaleffects`, and that there are no duplicate entries. I think both assumptions are unsafe.

This works fine:

```{r}
#| error: true
library(marginaleffects)
m <- lm(mpg ~ factor(cyl) * factor(am) + hp, data = mtcars)

get_emmeans <- function(x) {
  lev <- lapply(insight::get_datagrid(x), unique)
  lev <- lev[!names(lev) %in% c("rowid", "rowidcf", "marginaleffects_wts_internal")]
  emmobj(coef(x), vcov(x), lev)
}

x <- avg_predictions(m, by = c("cyl", "am"))
get_emmeans(x)
```

But if the original grid is unbalanced, we get an error:

```{r}
x <- predictions(m, newdata = data.frame(cyl = c(4, 6), am = 1:0, hp = 110))
get_emmeans(x)
```

Another issue is that some `marginaleffects` functions nearly always return unbalanced grids. For example:

```{r}
x <- avg_comparisons(m)
get_emmeans(x)
```

Any ideas? It feels like this may be more difficult than we initially thought...

**Comment by ngreifer** [comment]
Sorry, but from reading the last thread I can't really figure out what is missing from `marginaleffects` that would be gained by converting it to an `emmeans` object. Is there a specific quantity that can't be computed?

**Comment by vincentarelbundock** [comment]
I think the argument is: (a) some quantities are *easier* to compute with `emmeans` than with `marginaleffects` and (b) it's easy to convert objects to `emmeans` format.

If it were very easy, I'd be open to including a helper function to do so for convenience, so this issue is an exploration of that possibility.

But having looked at this for a couple hours now, I'm not convinced that it is so easy after all to convert...

**Comment by mattansb** [comment]
I'm on vacation, so excuse the brevity.

I was also thinking about this since we started the thread. I think it's pretty easy to coarse most avg_* to an emmGrid or emm_list. For non avg functions, we can either aggravate internally or decide not to support these.

I've played around with this and found it useful. Let's discuss when I get back (:

**Comment by vincentarelbundock** [comment]
Cool, no rush at all.

FWIW, if we go this route, my desiderata are: very strict, very safe, informative errors, very low code complexity (I don't want to maintain a 100-lines long function.)

**Comment by mattansb** [comment]
Looking back at this I agree with all of your points. I think this function would have to look something like this:

```R
as_emmean <- function(x, ...) {
  # test that x is not from a Bayesian model
  ...
  
  # test that x is a grid
  ...
  
  # find if x contains degrees of fredom
  df <- ...
  
  lev <- lapply(insight::get_datagrid(x), unique)
  lev <- lev[!names(lev) %in% c("rowid", "rowidcf", "marginaleffects_wts_internal")]
  # order list/items to what emmeans in expecting
  ...
  
  emmobj(coef(x), vcov(x), lev, df = df, ...)
}
```

A grid is a data frame that contains all possible combinations of non-constant variables. I've already implemented [something like this](https://github.com/strengejacke/ggeffects/blob/45a005d6daf8e01296d342ece0f76b60642e9041/R/residualize_over_grid.R#L141) for `ggeffects::residualize_over_grid()` so that should be easy. 

---

@ngreifer, what is currently "missing" from `marginaleffects` is the ability to _easily_ apply a range of contrasts that is supported (post-estimation) by `emmeans` (and some joint-test capabilities), as I've listed in the opening post here #1232. I say "_easily_", because while `marginaleffects` supports arbitrary contrasts via function writing (allowing for things that `emmeans` cannot support), a lot of contrasts (at least those commonly used in the experimental fields in which I was "brought up") are natively supported by `emmeans` and more accessible to the user.

I think an in-house solution would be so to expand the post-estimation capabilities of the `hypotheses()` function, which might be something we / you can do in more distant future. But for now, I think adding this function is a good (temporary?) compromise for the "how do I do this thing I know from `emmeans`"-crowd (myself included).

**Comment by vincentarelbundock** [comment]
I guess I'm still not sure on the benefits in terms of workflow.

If someone is already so comfortable with `emmeans` that they know how to run very complex contrasts that are not available (easily) in `marginaleffects`, isn't it easier to just specify the contrast from scratch in `emmeans`? 

I worry that allowing this conversion just adds another "abstraction layer" between the user input and the quantity. To know exactly what the quantity is, the user will have to figure out what `marginaleffects::comparisons()` does, what `insight::get_datagrid()` does, what `marginaleffects::get_emmeans()` does, and what `emmeans::contrast()` does. 

I would personally never use (and would strongly discourage other people to use) a function with so many layers, unless it brings **massive** convenience benefits. 

I worry that if we show the "from scratch" workflow side by side, with pure `emmeans` and `marginaleffects` conversion, the code will be essentially the same length, and no "clearer" in `marginaleffects`. If that's the case, then users should probably just use `emmeans`...

**Comment by vincentarelbundock** [comment]
Alright, tough decision time.

I think I'll pass on this. Maybe we can document this in the Alternative Software vignette? 

If someone ever writes a very robust version of this, I'll consider adding it, but it would have to be robust and nearly "feature complete", not a half-baked solution.

Very sorry to turn this down! I know you've invested a lot in this discussion and in thinking about this!

**Comment by mattansb** [comment]
Fair enough. No worries, as I said, I'm already using thus function for myself, so I don't fee like I wasted any time (:

I hope we can someday find the right was to copy some more of the `emmeans::contrast()` and `emmeans::joint_test()` functionality to `hypotheses()`. 🤞
