### ISSUE TITLE
Average contrasts in the presence of interactions

### ISSUE THREAD

**Issue by vmikk** [vincentarelbundock/marginaleffects#406]
Hello!
I'm trying to summarize unit-level contrasts by a categorical variable for a model with interactions.
However, it looks like the contrast names contain only a single combination in the results of `comparisons` function. 

Reproducible example:
```R
library(marginaleffects)
library(ggplot2)
library(plyr)

data(diamonds)
diamonds <- diamonds[1:1000, ]

## Convert to unordered factor levels
diamonds$cut <- factor(as.character(diamonds$cut), levels = levels(diamonds$cut))
diamonds$color <- factor(as.character(diamonds$color), levels = levels(diamonds$color))
diamonds$clarity <- factor(as.character(diamonds$clarity), levels = levels(diamonds$clarity))

mod <- lm(price ~ cut * color + clarity  + carat, data = diamonds)

## Unit-level contrasts
cmp <- comparisons(mod, variables = "cut")
```
If we look at the `contrast_cut` column, all combinations of `cut` levels are identical within each observation (e.g., **only `Good - Fair`** for the first record):
```R
subset(cmp, rowid == 1)
```
```
rowid     type        term contrast_cut   comparison ...
    1 response interaction  Good - Fair   321.5516  ...
    1 response interaction  Good - Fair   321.5516  ...
    1 response interaction  Good - Fair   321.5516  ...
    1 response interaction  Good - Fair   374.5386  ...
```

Therefore the summary estimates does not match the expected values:
```R
smr <- summary(cmp, by = "color")
smr
```

I've tried to reproduce unit-level estimates and predicted the values for each observation by changing only the `cut` variable:
```R
dm <- cbind(rowid = 1:nrow(diamonds), diamonds[, -2])

custom_contrasts <- function(x){

  Ideal <- predict(mod, newdata = cbind(cut = "Ideal", x))
  Premium <- predict(mod, newdata = cbind(cut = "Premium", x))
  VeryGood <- predict(mod, newdata = cbind(cut = "Very Good", x))
  Good <- predict(mod, newdata = cbind(cut = "Good",  x))
  Fair <- predict(mod, newdata = cbind(cut = "Fair",  x))
  
  ## Estimate contrasts
  res <- data.frame(
    color = x$color[1],
    Good_Fair = (Good - Fair)[[1]],
    VeryGood_Fair = (VeryGood - Fair)[[1]],
    Premium_Fair = (Premium - Fair)[[1]],
    Ideal_Fair = (Ideal - Fair)[[1]]
    )
  
  return(res)
}

CONTR <- adply(.data = dm, .margins = 1,
  .fun = custom_contrasts,
  .progress = "text")

## Group-average contrasts
CONTR_avg <- ddply(.data = CONTR, .variables = "color", .fun = function(x){
  data.frame(
    Good_Fair = mean(x$Good_Fair),
    VeryGood_Fair = mean(x$VeryGood_Fair),
    Premium_Fair = mean(x$Premium_Fair),
    Ideal_Fair = mean(x$Ideal_Fair))
  })

## The expected values
CONTR_avg
```

Compare the results with a simpler model without interactions (only for diamonds of one `color`):
```R
ds <- subset(diamonds, color %in% "E")
md <- lm(price ~ cut + clarity  + carat, data = ds)
cmp2 <- comparisons(md, variables = "cut")

summary(cmp2)                      # model without interactions

subset(smr, color %in% "E")        # results of marginaleffects::summary.comparisons
subset(CONTR_avg, color %in% "E")  # "custom" contrasts
```

So is it a bug in `comparisons`, and the `contrast` column should contain different combinations of predictor values for each rowid? Or is it not correct to estimate contrasts with interactions this way?

Thank you for all your hard work on this package!

PS. `marginaleffects` version 0.6.0

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report, I really appreciate it\!

It looks like you found a bug. I believe that the latest dev version should fix this problem. Could you please install from Github, restart R completely, and try again?

FYI, I used your code in the test suite to make sure this doesn’t happen again.

``` r
remotes::install_github("vincentarelbundock/marginaleffects")
```

``` r
library(marginaleffects)
library(ggplot2)
data(diamonds)
diamonds <- diamonds[1:1000, ]
diamonds$cut <- factor(as.character(diamonds$cut), levels = levels(diamonds$cut))
diamonds$color <- factor(as.character(diamonds$color), levels = levels(diamonds$color))
diamonds$clarity <- factor(as.character(diamonds$clarity), levels = levels(diamonds$clarity))
mod <- lm(price ~ cut * color + clarity  + carat, data = diamonds)

# single comparisons
comparisons(mod, variables = "cut") |> summary()
#> Average contrasts 
#>                cut Effect Std. Error z value   Pr(>|z|) 2.5 % 97.5 %
#> 1      Good - Fair  275.0      41.20   6.674 2.4977e-11 194.2  355.7
#> 2 Very Good - Fair  304.3      36.15   8.418 < 2.22e-16 233.5  375.2
#> 3   Premium - Fair  292.3      35.23   8.297 < 2.22e-16 223.2  361.3
#> 4     Ideal - Fair  420.1      35.07  11.977 < 2.22e-16 351.3  488.8
#> 
#> Model type:  lm 
#> Prediction type:  response

# interactions
comparisons(mod, variables = c("cut", "color")) |> summary()
#> Average contrasts 
#>                 cut color   Effect Std. Error z value   Pr(>|z|)   2.5 %
#> 1       Fair - Fair E - D  -434.75      145.2 -2.9932 0.00276028  -719.4
#> 2       Fair - Fair F - D  -364.48      140.9 -2.5873 0.00967350  -640.6
#> 3       Fair - Fair G - D  -464.59      147.7 -3.1445 0.00166395  -754.2
#> 4       Fair - Fair H - D  -708.12      138.8 -5.1034 3.3353e-07  -980.1
#> 5       Fair - Fair I - D  -874.12      146.0 -5.9879 2.1259e-09 -1160.2
#> 6       Fair - Fair J - D -1040.94      150.8 -6.9009 5.1666e-12 -1336.6
#> 7       Good - Fair D - D   -78.25      150.9 -0.5185 0.60413542  -374.1
#> 8       Good - Fair E - D  -113.20      133.2 -0.8498 0.39541206  -374.3
#> 9       Good - Fair F - D   -57.01      138.3 -0.4121 0.68026212  -328.2
#> 10      Good - Fair G - D  -213.88      143.6 -1.4892 0.13643728  -495.4
#> 11      Good - Fair H - D  -300.45      142.2 -2.1127 0.03462505  -579.2
#> 12      Good - Fair I - D  -499.58      143.7 -3.4761 0.00050870  -781.3
#> 13      Good - Fair J - D  -670.92      145.7 -4.6036 4.1526e-06  -956.6
#> 14 Very Good - Fair D - D    24.30      131.2  0.1851 0.85312537  -232.9
#> 15 Very Good - Fair E - D   -53.72      129.8 -0.4138 0.67900624  -308.2
#> 16 Very Good - Fair F - D   -89.46      129.6 -0.6903 0.48999200  -343.5
#> 17 Very Good - Fair G - D  -153.33      133.1 -1.1517 0.24942656  -414.3
#> 18 Very Good - Fair H - D  -318.37      132.3 -2.4065 0.01610578  -577.7
#> 19 Very Good - Fair I - D  -482.39      138.9 -3.4737 0.00051335  -754.6
#> 20 Very Good - Fair J - D  -640.94      143.7 -4.4592 8.2281e-06  -922.7
#> 21   Premium - Fair D - D    75.11      131.5  0.5712 0.56783364  -182.6
#> 22   Premium - Fair E - D    13.02      128.4  0.1014 0.91925367  -238.7
#> 23   Premium - Fair F - D   -48.63      128.8 -0.3777 0.70567161  -301.0
#> 24   Premium - Fair G - D  -209.25      131.1 -1.5963 0.11041441  -466.2
#> 25   Premium - Fair H - D  -494.96      132.9 -3.7255 0.00019495  -755.4
#> 26   Premium - Fair I - D  -598.50      135.3 -4.4238 9.6994e-06  -863.7
#> 27   Premium - Fair J - D  -705.23      139.7 -5.0469 4.4903e-07  -979.1
#> 28     Ideal - Fair D - D   136.78      130.2  1.0508 0.29335755  -118.3
#> 29     Ideal - Fair E - D    99.61      129.1  0.7718 0.44021569  -153.3
#> 30     Ideal - Fair F - D    91.58      128.7  0.7114 0.47683159  -160.7
#> 31     Ideal - Fair G - D  -129.74      129.6 -1.0013 0.31669948  -383.7
#> 32     Ideal - Fair H - D  -244.44      130.7 -1.8702 0.06146074  -500.6
#> 33     Ideal - Fair I - D  -434.17      130.8 -3.3186 0.00090480  -690.6
#> 34     Ideal - Fair J - D  -501.73      150.7 -3.3298 0.00086911  -797.1
#>     97.5 %
#> 1  -150.08
#> 2   -88.37
#> 3  -175.01
#> 4  -436.17
#> 5  -588.00
#> 6  -745.29
#> 7   217.57
#> 8   147.87
#> 9   214.13
#> 10   67.61
#> 11  -21.72
#> 12 -217.90
#> 13 -385.28
#> 14  281.52
#> 15  200.73
#> 16  164.54
#> 17  107.60
#> 18  -59.08
#> 19 -210.21
#> 20 -359.22
#> 21  332.82
#> 22  264.70
#> 23  203.75
#> 24   47.67
#> 25 -234.56
#> 26 -333.33
#> 27 -431.36
#> 28  391.90
#> 29  352.56
#> 30  343.90
#> 31  124.22
#> 32   11.74
#> 33 -177.75
#> 34 -206.41
#> 
#> Model type:  lm 
#> Prediction type:  response
```

**Comment by vincentarelbundock** [comment]
Will close now to clean the repository, but please feel free to re-open or to keep commenting if there are still issues.

I really appreciate you reporting this!

**Comment by vmikk** [comment]
Hello!
Thank you very much for your response and the bug fix!
I've installed the latest dev version from the `main` branch (25312fbe88a). However, the problem remains.

As I understand, by default, contrasts for each level of the categorical variables should be estimated relative to the baseline category (e.g., `Fair` for this dataset).
However, suppose we specify **`pairwise`** comparison type. In that case, all 10 comparison combinations (e.g., `Very Good - Fair`, `Premium - Fair`, `Ideal - Fair`, etc.) should be present in the `contrast_cut` column for each record ("unit-level contrasts"), isn't it?
Currently, `contrast_cut` contains only a single comparison label, but `comparison` values are different, so I assume the labels are wrong.

E.g., contrasts for the first record:
```
cmp <- comparisons(mod, variables = list(cut = "pairwise"))
subset(cmp, rowid == 1)

#>    rowid     type        term contrast_cut comparison ...
#> 1      1 response interaction  Good - Fair   321.5516 ...
#> 2      1 response interaction  Good - Fair   321.5516 ...
#> 3      1 response interaction  Good - Fair   321.5516 ...
#> 4      1 response interaction  Good - Fair   374.5386 ...
#> 5      1 response interaction  Good - Fair   370.0144 ...
#> 6      1 response interaction  Good - Fair   370.0144 ...
#> 7      1 response interaction  Good - Fair   374.5386 ...
#> 8      1 response interaction  Good - Fair   407.6720 ...
#> 9      1 response interaction  Good - Fair   321.5516 ...
#> 10     1 response interaction  Good - Fair   407.6720 ...
```

**Comment by vincentarelbundock** [comment]
Wow, this is embarassing\!

Could you please try the latest Github version from this morning?

``` r
library(marginaleffects)
library(ggplot2)
data(diamonds)
diamonds <- diamonds[1:1000, ]
diamonds$cut <- factor(as.character(diamonds$cut), levels = levels(diamonds$cut))
diamonds$color <- factor(as.character(diamonds$color), levels = levels(diamonds$color))
diamonds$clarity <- factor(as.character(diamonds$clarity), levels = levels(diamonds$clarity))
mod <- lm(price ~ cut * color + clarity  + carat, data = diamonds)
comparisons(mod, variables = list(cut = "pairwise")) |> 
    subset(rowid == 1, select = 1:5)
#>      rowid     type        term        contrast_cut comparison
#> 1        1 response interaction         Good - Fair  321.55156
#> 1001     1 response interaction    Very Good - Fair  381.02831
#> 2001     1 response interaction      Premium - Fair  447.76976
#> 3001     1 response interaction        Ideal - Fair  534.36151
#> 4001     1 response interaction    Very Good - Good   59.47675
#> 5001     1 response interaction      Premium - Good  126.21821
#> 6001     1 response interaction        Ideal - Good  212.80996
#> 7001     1 response interaction Premium - Very Good   66.74146
#> 8001     1 response interaction   Ideal - Very Good  153.33321
#> 9001     1 response interaction     Ideal - Premium   86.59175
```

**Comment by vmikk** [comment]
With the latest commit (930c0abe9a585b) everything works perfectly!
Thank you so much!
