### ISSUE TITLE
Population-level predictions with lme4: binomial likelihood

### ISSUE THREAD

**Issue by arthur-albuquerque** [vincentarelbundock/marginaleffects#436]
Hi Vincent,

I want to generate population-level predictions from logistic regression with random intercepts. I followed your nice [vignette](https://vincentarelbundock.github.io/marginaleffects/articles/lme4.html#population-level-predictions), but it is not working. In the reprex below, I use {marginaleffects} v.6.0. I also tried with dev version 0.6.0.9 without success.

The culprit might be the dataset’s format (aggregate binomial). However, for this type of analysis, I cannot convert it to the Bernoulli format (`0, 1, 0...`).

Is this a bug or am I doing something wrong?

Thanks!

----------------------------------------------------------------------------------------------------------------------------------

``` r
library(marginaleffects)
library(lme4)
#> Loading required package: Matrix
library(emmeans)
```

Load data

``` r
# e = number of events
# n = total

data <- data.frame(e = c(1, 1, 134413, 92622, 110747,
                         3625, 35, 64695, 19428, 221, 913, 13, 5710, 121,
                         1339, 1851, 637, 20, 7, 10, 2508),
                   n = c(165, 143, 10458616, 5338995, 6018504, 190810,
                         1607, 2504824, 471821, 5158, 15027, 205, 86371, 1785,
                         10661, 14406, 4048, 102, 916, 1079, 242715),
                   year = round(runif(21, min = 1, max = 24)),
                   sid = as.factor(1:21))
```

Fit model

``` r
m = 
  glmer(cbind(e, n - e) ~ 1 + year + (1 | sid), data = data,
        family = binomial()) 
```

I first checked if `predictions()` worked fine, and it does.

``` r
predictions(m) |> 
  head()
#>   rowid     type  predicted   std.error    conf.low  conf.high year sid      e
#> 1     1 response 0.01182941 0.002774726 0.007461553 0.01870595   11   1      1
#> 2     2 response 0.01302607 0.003051715 0.008220036 0.02058374   11   2      1
#> 3     3 response 0.01285198 0.003089399 0.008013368 0.02055170   14   3 134413
#> 4     4 response 0.01734832 0.004046523 0.010965288 0.02734427   11   4  92622
#> 5     5 response 0.01840119 0.005625638 0.010078679 0.03336442   18   5 110747
#> 6     6 response 0.01900022 0.006819620 0.009366330 0.03816148    4   6   3625
#>          n
#> 1      165
#> 2      143
#> 3 10458616
#> 4  5338995
#> 5  6018504
#> 6   190810
```

I then noticed that `datagrid` wasn’t compatible with my dataset. Is it because
of `cbind(...)` within `glmer`?

``` r
predictions(m, 
            newdata = datagrid(year = 1:24,
                                  sid = NA),
            include_random = FALSE)
#> Error: 
#> The `datagrid()`, `marginalmeans()`, `plot_cap()`, and `plot_cme()` functions
#> do not support datasets with matrix columns. You can construct your own
#> prediction dataset and supply it explicitly to the `newdata` argument of the
#> `predictions()`, `marginaleffects()`, or `comparisons()` functions instead.
```

It doesn’t work by constructing a separate prediction dataset either.

``` r
nd = data.frame(year = 1:24, sid = NA)

predictions(m,
            newdata = nd,
            include_random = FALSE)
#> Warning: Invalid grouping factor specification, sid
#> Error: 
#> Unable to compute adjusted predictions for model of class `glmerMod`. You can try to
#> specify a different value for the `newdata` argument. If this does not work and
#> you believe that this model class should be supported by `marginaleffects`,
#> please file a feature request on the Github issue tracker:
#> 
#> https://github.com/vincentarelbundock/marginaleffects/issues
```

“Warning: Invalid grouping factor specification, sid”

It looks like it is not compatible with the `sid = NA`.

On the other hand, following @ASKurz [code with emmeans](https://solomonkurz.netlify.app/post/2021-12-16-use-emmeans-to-include-95-cis-around-your-lme4-based-fitted-lines/) (which inspired the vignette mentioned above),
it works as expected.

``` r
emmeans(
  object = m, 
  specs = ~ year, 
  at = list(year = seq(from = 1, to = 24, by = 1)), 
  lmer.df = "satterthwaite") |> 
  data.frame() |> 
  head()
#>   year    emmean        SE  df asymp.LCL asymp.UCL
#> 1    1 -3.509055 0.4508487 Inf -4.392702 -2.625408
#> 2    2 -3.496466 0.4215678 Inf -4.322723 -2.670208
#> 3    3 -3.483877 0.3931743 Inf -4.254484 -2.713269
#> 4    4 -3.471287 0.3658749 Inf -4.188389 -2.754186
#> 5    5 -3.458698 0.3399334 Inf -4.124955 -2.792441
#> 6    6 -3.446109 0.3156847 Inf -4.064839 -2.827378
```

``` r
sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.7
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] emmeans_1.7.4-1       lme4_1.1-29           Matrix_1.4-1         
#> [4] marginaleffects_0.6.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.8.3      compiler_4.1.2    nloptr_2.0.3      tools_4.1.2      
#>  [5] boot_1.3-28       digest_0.6.29     checkmate_2.1.0   evaluate_0.15    
#>  [9] nlme_3.1-158      lattice_0.20-45   rlang_1.0.4       reprex_2.0.1     
#> [13] cli_3.3.0         rstudioapi_0.13   yaml_2.3.5        mvtnorm_1.1-3    
#> [17] xfun_0.31         fastmap_1.1.0     coda_0.19-4       withr_2.5.0      
#> [21] stringr_1.4.0     knitr_1.39        generics_0.1.3    fs_1.5.2         
#> [25] grid_4.1.2        glue_1.6.2        data.table_1.14.3 survival_3.3-1   
#> [29] rmarkdown_2.14    multcomp_1.4-19   TH.data_1.1-1     minqa_1.2.4      
#> [33] magrittr_2.0.3    backports_1.4.1   codetools_0.2-18  htmltools_0.5.2  
#> [37] MASS_7.3-57       splines_4.1.2     insight_0.18.0.2  xtable_1.8-4     
#> [41] sandwich_3.0-2    stringi_1.7.6     estimability_1.3  zoo_1.8-10
```

<sup>Created on 2022-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Thanks for the report.

The reason your handmade data frame doesn't work is that `sid` needs to be a factor but it is logical in the data frame you constructed. Note that:

```r
> class(NA)
[1] "logical"
```

I just pushed a new commit to Github which should fix those other issues. Could you please install from Github, restart R, and try again?

**Comment by arthur-albuquerque** [comment]
Thanks for the quick reply. I installed from GitHub but the error persisted. 

Of note, the dataset used in your vignette also has a column classified as factor for the random intercept ("Chick") and the NA still works.

Nevertheless, here is my lastest try with my dataset:

``` r
remotes::install_github("vincentarelbundock/marginaleffects",
                        force = TRUE)

library(marginaleffects)
library(lme4)
#> Loading required package: Matrix

data <- data.frame(e = c(1, 1, 134413, 92622, 110747,
                         3625, 35, 64695, 19428, 221, 913, 13, 5710, 121,
                         1339, 1851, 637, 20, 7, 10, 2508),
                   n = c(165, 143, 10458616, 5338995, 6018504, 190810,
                         1607, 2504824, 471821, 5158, 15027, 205, 86371, 1785,
                         10661, 14406, 4048, 102, 916, 1079, 242715),
                   year = round(runif(21, min = 1, max = 24)),
                   sid = as.factor(1:21))


m = 
  glmer(cbind(e, n - e) ~ 1 + year + (1 | sid), data = data,
        family = binomial()) 

nd = data.frame(year = 1:24, sid = as.factor(NA))

predictions(m,
            newdata = nd,
            include_random = FALSE)
#> Warning: error in evaluating the argument 'x' in selecting a method for function
#> 't': assignment of an object of class "numeric" is not valid for @'Dim' in an
#> object of class "dgTMatrix"; is(value, "integer") is not TRUE
#> Error: 
#> Unable to compute adjusted predictions for model of class `glmerMod`. You can try to
#> specify a different value for the `newdata` argument. If this does not work and
#> you believe that this model class should be supported by `marginaleffects`,
#> please file a feature request on the Github issue tracker:
#> 
#> https://github.com/vincentarelbundock/marginaleffects/issues
```

``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.4 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
#> LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3
#> 
#> locale:
#>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
#>  [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
#>  [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
#> [10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] lme4_1.1-30                Matrix_1.4-1              
#> [3] marginaleffects_0.6.0.9000
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9        rstudioapi_0.13   knitr_1.39        magrittr_2.0.3   
#>  [5] splines_4.2.1     MASS_7.3-57       insight_0.18.0    lattice_0.20-45  
#>  [9] rlang_1.0.4       fastmap_1.1.0     minqa_1.2.4       stringr_1.4.0    
#> [13] tools_4.2.1       grid_4.2.1        checkmate_2.1.0   nlme_3.1-157     
#> [17] data.table_1.14.2 xfun_0.31         cli_3.3.0         withr_2.5.0      
#> [21] htmltools_0.5.3   remotes_2.4.2     yaml_2.3.5        digest_0.6.29    
#> [25] nloptr_2.0.3      fs_1.5.2          glue_1.6.2        evaluate_0.15    
#> [29] rmarkdown_2.14    reprex_2.0.1      stringi_1.7.8     compiler_4.2.1   
#> [33] backports_1.4.1   generics_0.1.3    boot_1.3-28
```

<sup>Created on 2022-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
It is not sufficient to use `as.factor(NA)`. You need to set all the correct levels of the factor too. In the vignette, this works because `datagrid()` takes care of the full `NA`-to-factor conversion work for you automatically, including setting the appropriate levels. 

Using version 0.6.0.9001 of the package, the `datagrid()` function should now work and you should just replace your `data.frame()` call by:

```r
nd = datagrid(year = 1:24, sid = NA)
```

**Comment by arthur-albuquerque** [comment]
Got it! Working like a charm now, thank you very much.

There is a warning message "Matrix columns are not supported and are omitted." Should I worry about that? Not sure if I understood it.

``` r
library(marginaleffects)
library(lme4)
#> Loading required package: Matrix
library(ggplot2)


data <- data.frame(e = c(1, 1, 134413, 92622, 110747,
                         3625, 35, 64695, 19428, 221, 913, 13, 5710, 121,
                         1339, 1851, 637, 20, 7, 10, 2508),
                   n = c(165, 143, 10458616, 5338995, 6018504, 190810,
                         1607, 2504824, 471821, 5158, 15027, 205, 86371, 1785,
                         10661, 14406, 4048, 102, 916, 1079, 242715),
                   year = round(runif(21, min = 1, max = 24)),
                   sid = as.factor(1:21))

m = 
  glmer(cbind(e, n - e) ~ 1 + year + (1 | sid), data = data,
        family = binomial()) 

predictions(m, 
            newdata = datagrid(year = 1:24,
                                  sid = NA),
            include_random = FALSE) |> 
  head()
#> Warning: 
#> Matrix columns are not supported and are omitted. This may prevent computation
#> of the quantities of interest. You can construct your own prediction dataset and
#> supply it explicitly to the `newdata` argument.
#>   rowid     type  predicted   std.error    conf.low  conf.high        e       n
#> 1     1 response 0.02324138 0.011042086 0.009088184 0.05814232 20900.81 1207998
#> 2     2 response 0.02394753 0.010646615 0.009947930 0.05652378 20900.81 1207998
#> 3     3 response 0.02467459 0.010234546 0.010873219 0.05501959 20900.81 1207998
#> 4     4 response 0.02542315 0.009809825 0.011863583 0.05363943 20900.81 1207998
#> 5     5 response 0.02619381 0.009378076 0.012916063 0.05239656 20900.81 1207998
#> 6     6 response 0.02698718 0.008947173 0.014024125 0.05130897 20900.81 1207998
#>   year  sid
#> 1    1 <NA>
#> 2    2 <NA>
#> 3    3 <NA>
#> 4    4 <NA>
#> 5    5 <NA>
#> 6    6 <NA>
  
sessionInfo()
#> R version 4.1.2 (2021-11-01)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Catalina 10.15.7
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] ggplot2_3.3.6              lme4_1.1-29               
#> [3] Matrix_1.4-1               marginaleffects_0.6.0.9001
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.8.3      pillar_1.7.0      compiler_4.1.2    nloptr_2.0.3     
#>  [5] highr_0.9         tools_4.1.2       boot_1.3-28       digest_0.6.29    
#>  [9] checkmate_2.1.0   tibble_3.1.7      evaluate_0.15     lifecycle_1.0.1  
#> [13] nlme_3.1-158      gtable_0.3.0      lattice_0.20-45   pkgconfig_2.0.3  
#> [17] rlang_1.0.4       reprex_2.0.1      DBI_1.1.3         cli_3.3.0        
#> [21] rstudioapi_0.13   yaml_2.3.5        xfun_0.31         fastmap_1.1.0    
#> [25] dplyr_1.0.9       withr_2.5.0       stringr_1.4.0     knitr_1.39       
#> [29] vctrs_0.4.1       generics_0.1.3    fs_1.5.2          tidyselect_1.1.2 
#> [33] grid_4.1.2        glue_1.6.2        data.table_1.14.3 R6_2.5.1         
#> [37] fansi_1.0.3       rmarkdown_2.14    minqa_1.2.4       purrr_0.3.4      
#> [41] magrittr_2.0.3    backports_1.4.1   ellipsis_0.3.2    scales_1.2.0     
#> [45] htmltools_0.5.2   MASS_7.3-57       splines_4.1.2     insight_0.18.0.4 
#> [49] assertthat_0.2.1  colorspace_2.0-3  utf8_1.2.2        stringi_1.7.6    
#> [53] munsell_0.5.0     crayon_1.5.1
```

<sup>Created on 2022-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
This is a warning because your prediction data grid includes matrix columns, and `marginaleffects` doesn't know how to manipulate those, so they are omitted entirely. Whether this is appropriate or dangerous probably depends on the exact nature of the model. In this particular case, I don't think it's a problem, but the warning is there to make sure that users take appropriate precautions.
